import { test, expect } from 'bun:test';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { PGLiteEngine } from '../src/core/pglite-engine.ts';
import { operationsByName } from '../src/core/operations.ts';
import { enrollPageFileRuntime, resolvePageFileRuntime } from '../src/core/page-file-runtime.ts';
import { withLegacyPageFileRootMutation } from '../src/core/page-file-root-gate.ts';
import { runPull } from '../src/commands/sources-harden.ts';
import { hardenBrainRepo } from '../src/core/brain-repo-durability.ts';
import { performSync } from '../src/commands/sync.ts';
import { runImport } from '../src/commands/import.ts';
import { withEnv } from './helpers/with-env.ts';

test('registered CAS to actual source pull to import command to checked reread preserves pending files', async () => {
 const home = await mkdtemp(join(tmpdir(),'root-runtime-')); const root=join(home,'source');
 const engine=new PGLiteEngine();
 const git=(...args:string[])=>execFileSync('git',['-C',root,...args],{env:{...process.env,GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1'},stdio:'pipe'}).toString().trim();
 try {
  await mkdir(root); await mkdir(join(home,'journal')); await mkdir(join(home,'.gbrain'));
  const config:any={engine:'pglite',page_file_runtime:{mode:'isolated-integration',topology:'single-host-local',brainId:'offline',lockDirectory:join(home,'locks'),journalDirectory:join(home,'journal')}};
  await writeFile(join(home,'.gbrain/config.json'),JSON.stringify(config));
  await engine.connect({}); await engine.initSchema();
  await engine.executeRaw("UPDATE sources SET local_path=$1 WHERE id='default'",[root]);
  const page={type:'concept',title:'Example',compiled_truth:'Before',timeline:'',frontmatter:{}};
  await engine.putPage('example',page); await writeFile(join(root,'example.md'),'Before');
  const ctx:any={engine,config,remote:false,sourceId:'default',dryRun:false,logger:{info(){},warn(){},error(){},debug(){}}};
  await enrollPageFileRuntime(ctx,'default','example');
  const call=(name:string,p:any)=>operationsByName[name].handler(ctx,p) as Promise<any>;
  const target={source_id:'default',slug:'example'};
  const before=await call('get_page_checked',target);
  expect((await call('put_page_checked',{...target,expected_revision:before.revision,page:{...page,compiled_truth:'Checked'},operation_id:randomUUID(),file_baseline:before.file.baseline,raw_markdown:'Checked'})).status).toBe('committed');
  git('init','-b','main'); git('config','user.name','Test'); git('config','user.email','test@example.invalid'); git('add','.'); git('commit','-m','checked fixture');
  git('checkout','-b','incoming'); await writeFile(join(root,'example.md'),'Pulled'); await writeFile(join(root,'other.md'),'Unrelated'); git('add','.');git('commit','-m','incoming fixture');git('checkout','main');git('remote','add','origin',root);
  const runtime=(await resolvePageFileRuntime(ctx,'default','example'))!;
  const stale=await runtime.sync.capture('default','example');
  await withEnv({GBRAIN_HOME:home,GBRAIN_GIT_ALLOW_FILE_TRANSPORT:'1'},async()=>{
   await runPull(engine,['default','--branch','incoming']);
   expect(await readFile(join(root,'example.md'),'utf8')).toBe('Pulled');
   expect((await engine.getPage('example'))!.compiled_truth).toBe('Checked');
   await expect(runtime.sync.commit(stale)).rejects.toMatchObject({acknowledgeable:false});
   const result=await runImport(engine,[root,'--no-embed','--workers','1'],{sourceId:'default'});
   expect(result.failures).toEqual([]);
   expect((await call('get_page_checked',target)).file.raw_markdown).toBe('Pulled');
   expect((await engine.getPage('other'))!.compiled_truth).toBe('Unrelated');
   const report=await hardenBrainRepo({engine,repoPath:root,sourceId:'default',branch:'incoming',dryRun:true,installCron:false,verify:false});
   expect(report.steps.find(s=>s.step==='pull')?.status).toBe('ok');
   const host={root,lockDirectory:config.page_file_runtime.lockDirectory,topology:'single-host-local' as const};
   const clean=await call('get_page_checked',target);
   const captured=await runtime.sync.capture('default','example');
   await expect(withLegacyPageFileRootMutation(engine,root,()=>{throw new Error('interrupted');},host)).rejects.toThrow('interrupted');
   await expect(call('get_page_checked',target)).rejects.toThrow('page_file_root_sync_required');
   const [generation]=await engine.executeRaw<{file_generation:string}>('SELECT file_generation FROM page_file_bindings');
   clean.file.baseline.generation=String(generation.file_generation);
   await expect(call('put_page_checked',{...target,expected_revision:clean.revision,page:{...page,compiled_truth:'Denied'},operation_id:randomUUID(),file_baseline:clean.file.baseline,raw_markdown:'Denied'})).rejects.toThrow('page_file_root_sync_required');
   await expect(runtime.sync.capture('default','example')).rejects.toThrow('page_file_root_sync_required');
   await expect(runtime.sync.commit(captured)).rejects.toThrow('page_file_root_sync_required');
   await expect(enrollPageFileRuntime(ctx,'default','other')).rejects.toThrow('page_file_root_sync_required');
   expect(await readFile(join(root,'example.md'),'utf8')).toBe('Pulled');
   await expect(runPull(engine,['default','--recover-root'])).rejects.toThrow('root_recovery_approval_required');
   await runPull(engine,['default','--recover-root','--yes']);
   expect((await call('get_page_checked',target)).file.raw_markdown).toBe('Pulled');
   await engine.executeRaw("UPDATE page_file_bindings SET pending_op_id='00000000-0000-0000-0000-000000000001'");
   await writeFile(join(root,'example.md'),'Pending authored bytes');
   await expect(runPull(engine,['default','--branch','incoming'])).rejects.toThrow('pending_recovery');
   const bookmark=await engine.getConfig('sync.last_commit');
   await expect(performSync(engine,{repoPath:root,sourceId:'default',noEmbed:true})).rejects.toThrow('pending_recovery');
   expect(await engine.getConfig('sync.last_commit')).toBe(bookmark);
   expect(await readFile(join(root,'example.md'),'utf8')).toBe('Pending authored bytes');
  });
 } finally {await engine.disconnect();await rm(home,{recursive:true,force:true});}
},60000);
