export const ru = {
  studioTitle: 'Студия Source Ingest',
  studioSubtitle: 'Каталог подключений, преобразований и публикаций',
  refreshSelected: 'Обновить выбранный раздел',
  collapse: 'Свернуть',
  expandAll: 'Развернуть всё',
  searchPlaceholder: 'Поиск по каталогу…',
  found: 'Найдено',
  catalogObjects: 'объектов каталога',
  enabled: 'включено',
  disabled: 'выключено',
  sections: {
    connectors: '1 · Подключения',
    baseViews: '2 · Источники',
    transformViews: '3 · Преобразования',
    articleViews: '4 · Публикации',
    schema: '5 · Схема мозга',
  },
  meta: {
    connections: 'подключений',
    sourceTables: 'источников',
    sqlViews: 'преобразований',
    publishProfiles: 'публикаций',
    schemaTypes: 'типов',
    fields: 'полей',
    inputs: 'входов',
    lastRun: 'посл. запуск',
    why: 'причина',
    readOnly: 'только чтение',
  },
  newItems: {
    connector: 'Новое подключение…',
    connectorMeta: 'тип + секреты + проверка',
    baseView: 'Новый источник…',
    baseViewMeta: 'подключение + таблица + поля',
    transformView: 'Новое преобразование…',
    transformViewMeta: 'алиасы + SQL-preview',
    articleView: 'Новая публикация…',
    articleViewMeta: 'схема + шаблон + батч',
  },
  schemaOverview: 'Обзор схемы',
} as const;
